name: diplom
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  


dependencies:
  flutter:
    sdk: flutter
 

  cupertino_icons: ^1.0.2
  provider: any
  http: ^1.2.0
  shared_preferences: ^2.2.2
  rebirth: ^1.0.2
  file_picker: ^8.0.3
  dio: any
  fast_cached_network_image: ^1.2.9
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 
  fonts:
    - family: Jojo
      fonts:
        - asset: assets/fonts/jejuhallasan.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 